### ISSUE TITLE
CSS Selector | 雪中印

### ISSUE THREAD

**Issue by GeekEast** [GeekEast/blog_comment#77]
https://geekeast.github.io/cssselector.html 

 CSS Selector    Example Description Stress     .btn Select all elements with class=“btn” 类   #firstname Selects the element with id=“firstname” ID   * Selects all elements 继承断层时应用   p Selects all &lt

**Comment by GeekEast** [comment]
### 常见的伪类选择器
`p::first-letter`: 第一个字母

`p::first-line`： 第一行

`p::first-selection`： 选中

`div::before`：之前 + content(string)

`div::after`： 之后 + content(string)

**Comment by GeekEast** [comment]
### CSS中选择器书写规范：
- 多个selector（或），每个选择器声明必须独占一行
```css
.post,
.page,
.comment {
  line-height: 1.5;
}
```
- 嵌套层级最好不要超过3级
```css
.nav li a {
  color: red
}
```
